encoding: UTF-8
lang: en
title: Spyros' tech blog
email:
description:
baseurl: # the optional subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Spyros Giannakakis
  twitter:
  picture:
twitter_username: spy_gi
github_username: spygi
google_analytics: UA-119134259-1
disqus:
    shortname: spygi

logo: # path of site logo, e.g. "/assets/images/logo.png"
search: true # basically-basic theme: for site-wide search
search_full_content: true # to index all posts and not only the first 50 words
permalink: /:categories/:title/ # same as none

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true

# Build settings
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3
remote_theme: mmistakes/jekyll-theme-basically-basic # used locally and on Github pages
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "starter-kit", "vendor"]
whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
feed:
  path: atom.xml
sass:
  style: compressed
